codecov:
  # Avoid "Missing base report" due to committing CHANGES.rst with "[CI skip]"
  # https://github.com/codecov/support/issues/363
  # https://docs.codecov.io/docs/comparing-commits
  allow_coverage_offsets: true

  token: 78b19480-8cfa-4f32-8448-b972a29a8f46