name: Build
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        sudo DISKO_INTEGRATION=run go test -v -race -covermode=atomic -coverprofile coverage.txt ./...

    - name: Upload Coverage report to CodeCov
      if: success()
      uses: codecov/codecov-action@v1.0.0
      with:
        token: 78b19480-8cfa-4f32-8448-b972a29a8f46
        file: ./coverage.txt
